export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
